### PR TITLE
added section about async methods and ReadMe and also code in demo

### PR DESCRIPTION
**Pull request by mhoegger**
did not invest too much time into proofreading my extension, might have some typos. However code sould be executable and working

### CODE REVIEW

**Review by joelbarmettlerUZH — COMMENTED** [review]
What role does the 'CompletableFuture<List<***>>' play? Can we make other api calls while the asynchronous one is still performing - like making an api request that takes 30 seconds, but making a few other requests in the meanwhile?

**Comment by mhoegger** [comment]
As far as my understanding goes it is a interface that enables to work such async methods. over this interface the methods can be composed, combined and so on. (http://www.baeldung.com/java-completablefuture). However I'm not sure if it is needed, might be possible to use async calls without that interface. 
The use of the async in the example is relatively independent of the api, other than that the api calls the async method. 
According to literature this implementation should enable non-blocking request. However the example code in the demo does not prove that, you're right.

**Comment by joelbarmettlerUZH** [comment]
Can you add an example demonstrating the non-blocking feature, and maybe add the link to (http://www.baeldung.com/java-completablefuture) OR try a quick test whether the asynch request could work without the CompletableFuture interface?

**Comment by mhoegger** [comment]
Just tried the non-blocking feature usinf multiple curls. seems not to work like intended. Will have to look further into it. Yes can test without CompletableFeature interface

**Comment by mhoegger** [comment]
I just tested it witout CompletableFeature: does not work. But I found out that if we exchange CompletableFeature with DeferredResult then the request are not blocking and a timeout can be given. however I think in that case when a new request comes in the longlasting one gets cancelled.

**Review by joelbarmettlerUZH — APPROVED** [review]

**Pull request merged**
